networks:
  backend:
    driver: bridge

volumes:
  pgadmin:    
  userdb:
  productdb:
  orderdb:
  purchasedb:

services:
  frontend:
    container_name: devil-cat_front-end
    image: ${DOCKER_REGISTRY-}frontend
    ports:
    - "3000:81" 
    - "3001:80"
    build:
      context: .
      dockerfile: frontend/Dockerfile
    networks:
      - backend
    depends_on:
      - userdata
      - productdata
      # - orderdata
      # - purchasedata

  backend:
    container_name: devil-cat_back-end
    image: ${DOCKER_REGISTRY-}backend
    ports:
    - "8000:81" 
    - "8001:80"
    build:
      context: .
      dockerfile: backend/Dockerfile
    networks:
      - backend
    depends_on:
      - userdata
      - productdata
      # - orderdata
      # - purchasedata

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@stiktify.store}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  userdata:
    container_name: user_db
    image: postgres
    ports:
      - "5432:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=userdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - userdb:/var/lib/postgresql/data
  
  productdata:
    container_name: product_db
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - productdb:/var/lib/postgresql/data
