networks:
  backend: 
    driver: bridge

volumes:
  pgadmin:    
  shopdata:
  productdata:
  orderdata:
  purchasedata:

services:
  devilcatclient:
    container_name: devil-cat-client
    image: ${DOCKER_REGISTRY-}devilcatclient
    ports:
      - "3000:8081"
      - "3080:8080"
    networks:
      - backend
    build:
      context: .
      dockerfile: DevilCatClient/Dockerfile
    depends_on:
      - devilcatbackend

  devilcatbackend:
    container_name: devil-cat-backend
    image: ${DOCKER_REGISTRY-}devilcatbackend
    ports:
      - "8000:8081"
      - "8080:8080"
    networks:
      - backend
    build:
      context: .
      dockerfile: DevilCatBackend/Dockerfile
    depends_on:
      - productdata

  pgadmin:
    container_name: postgre-admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@stiktify.store}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - backend
    restart: unless-stopped

  productdata:
    container_name: productdb
    image: postgres
    ports:
      - "5433:5432"
    networks:
      - backend
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin@123
    volumes:
      - productdata:/var/lib/postgresql/data

